### Obtener todos los contactos
GET http://localhost:3000/contacts


### Obtener un solo contacto por ID
GET http://localhost:3000/contacts/6abb34146282d92bcf71a2d3

### Obtener todos los contactos desde Render
GET https://cse341-fsmg.onrender.com/contacts


### Obtener un solo contacto por ID desde Render
GET https://cse341-fsmg.onrender.com/contacts/6abb34146282d92bcf71a2d3

### Crear un contacto
POST http://localhost:3000/contacts
Content-Type: application/json

{
  "firstName": "Alan",
  "lastName": "Krebs",
  "email": "alan@test.com",
  "favoriteColor": "blue",
  "birthday": "1985-01-01"
}


### Actualizar un contacto
PUT http://localhost:3000/contacts/6abb34146282d92bcf71a2d3
Content-Type: application/json

{
  "firstName": "Alan",
  "lastName": "Krebs",
  "email": "alankrebs@gmail.com",
  "favoriteColor": "blue",
  "birthday": "1985-23-01"
}
### Eliminar un contacto
DELETE http://localhost:3000/contacts/6ac6f578751082b7b314b3b3


### Crear contacto en Render
POST https://cse341-fsmg.onrender.com/contacts
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Render",
  "email": "test@render.com",
  "favoriteColor": "red",
  "birthday": "2000-01-01"
}
### Actualizar contacto en Render
PUT https://cse341-fsmg.onrender.com/contacts/6ac70024bbd9546f7fb7f971
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Render",
  "email": "test@render.com",
  "favoriteColor": "green",
  "birthday": "2000-01-01"
}

### Eliminar contacto en Render
DELETE https://cse341-fsmg.onrender.com/contacts/6ac70024bbd9546f7fb7f971